spring.application.name=payment-service
internal.api.shared-secret=change-me
security.jwt.secret=change-me

# Spring profiles
spring.profiles.group.dev=dev,common
spring.profiles.group.qa=qa,common
spring.profiles.group.prod=prod,common