spring.application.name=payment-service
internal.api.shared-secret=change-me
security.jwt.secret=change-me

# Spring profiles
spring.profiles.group.dev=dev,common
spring.profiles.group.qa=qa,common
spring.profiles.group.prod=prod,common
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/payment_service}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Razorpay configuration
payment.razorpay.base-url=${RAZORPAY_BASE_URL:https://api.razorpay.com}
payment.razorpay.key-id=${RAZORPAY_KEY_ID:rzp_test_change_me}
payment.razorpay.key-secret=${RAZORPAY_KEY_SECRET:change-me}
payment.razorpay.webhook-secret=${RAZORPAY_WEBHOOK_SECRET:change-me}
